export enum ErrorCode {
  'app/internal-error' = 'app/internal-error',
  'app/bad-request' = 'app/bad-request',
  'app/conflict' = 'app/conflict',
  'app/forbidden' = 'app/forbidden',
  'app/not-acceptable' = 'app/not-acceptable',
  'app/not-found' = 'app/not-found',
  'app/request-timeout' = 'app/request-timeout',
  'app/unauthorize' = 'app/unauthorize',
  'auth/invalid-password' = 'auth/invalid-password',
  'auth/already-registered' = 'auth/already-registered',
  'auth/token-expired' = 'auth/token-expired',
  'auth/invalid-token' = 'auth/invalid-token',
  'record/unfinished' = 'record/unfinished',
}
